INSERT INTO tb_authors (name, birthday, nationality, status) values('Robert T. Kiyosaki', 'April 8, 1947', 'Japenese-American','Empresário e escritor nipo-americano. Kiyosaki é o fundador da Rich Global LLC e da Rich Dad Company, uma empresa privada de educação financeira que fornece finanças pessoais e educação empresarial para pessoas através de livros e vídeos.')
INSERT INTO tb_authors (name, birthday, nationality, status) values('George Samuel Clason','November 7, 1874 – April 5, 1957', 'American', 'Foi um autor americano. Ele é mais frequentemente associado ao seu livro O Homem Mais Rico da Babilônia, que foi publicado pela primeira vez em 1926.')
INSERT INTO tb_authors (name, birthday, nationality, status) values('Jacob Petry','Julho 26, 1971','Brazilian', 'Jornalista, pesquisador e escritor brasileiro radicado nos Estados Unidos')
INSERT INTO tb_authors (name, birthday, nationality, status) values(' Brian Tracy ','January 5, 1944','Canadian', 'Foi um escritor e professor americano, e o desenvolvedor de cursos de auto-aperfeiçoamento, habilidade de vendas, treinamento corporativo, falar em público e habilidades interpessoais.')
INSERT INTO tb_authors (name, birthday, nationality, status) values(' Dale Carnegie ','November 24, 1888 - November 1, 1955,','American', 'Foi um escritor e professor americano, e o desenvolvedor de cursos de auto-aperfeiçoamento, habilidade de vendas, treinamento corporativo, falar em público e habilidades interpessoais.')
INSERT INTO tb_authors (name, birthday, nationality, status) values(' Morgan Housel','1990','American', 'Sócio do The Collaborative Fund. Ele é duas vezes vencedor do Prêmio de Melhor em Negócios da Sociedade de Editores de Negócios Americanos.')
INSERT INTO tb_authors (name, birthday, nationality, status) values(' T. Harv Eker','June 10, 1954','Canadian', 'Autor, empresário e palestrante motivacional conhecido por suas teorias sobre riqueza e motivação. Ele é o autor do livro Secrets of the Millionaire Mind, publicado pela HarperCollins.')
INSERT INTO tb_authors (name, birthday, nationality, status) values('Steve Harvey','17 de janeiro de 1957','American','Apresentador de televisão americano, produtor, ator e comediante. Ele apresenta o The Steve Harvey Morning Show, Family Feud, Celebrity Family Feud, Family Feud Africa, o juiz de comédia judicial baseado em arbitragem Steve Harvey, e ele anteriormente apresentou a competição Miss Universo.')

INSERT INTO tb_category (genre) values('Romance')
INSERT INTO tb_category (genre) values('Auto-Ajuda e Desenvolvimento Pessoal')
INSERT INTO tb_category (genre) values('Auto-Ajuda')
INSERT INTO tb_category (genre) values('Desenvolvimento Pessoal')
INSERT INTO tb_category (genre) values('Literatura')
INSERT INTO tb_category (genre) values('Didático')
INSERT INTO tb_category (genre) values('Finanças Pessoais')


INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('O homem mais rico da Babiônia', '1926', 'Harper Collins', 1,'https://cdn.kobo.com/book-images/6e3abd67-b02f-47ef-a49c-427d82d0ca80/1200/1200/False/o-homem-mais-rico-da-babilonia.jpg','Foi por volta de 1926 que o autor George S. Clason se lembrou de escrever alguns panfletos informativos sobre como alcançar o sucesso financeiro...','Foi por volta de 1926 que o autor George S. Clason se lembrou de escrever alguns panfletos informativos sobre como alcançar o sucesso financeiro, inspirando-se em parábolas ambientadas na antiga Babilónia, império indubitavelmente poderoso. Assim, Clason conta a história de um homem que quis tornar-se rico e o conseguiu através de cinco leis de ouro, que se tornaram um conjunto de princípios pedagógicos com validade intemporal.',2,3)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('As 16 leis do sucesso', '2017','Faro Editorial', 2,'https://m.media-amazon.com/images/I/71ZB2soKVgL._AC_UF1000,1000_QL80_.jpg','AS 16 LEIS DO SUCESSO é um curso prático que reúne as 16 poderosas lições que são as bases de toda filosofia de Napoleon Hill...','AS 16 LEIS DO SUCESSO é um curso prático que reúne as 16 poderosas lições que são as bases de toda filosofia de Napoleon Hill, o maior gênio na área da realização pessoal e psicologia aplicada de todos os tempos.',2,2)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('Pai rico, Pai pobre', '1997', 'Campus- Grupo Elsevier', 1,'https://img.bertrand.pt/images/pai-rico-pai-pobre-robert-t-kiyosaki/NDV8MTYwMzYzNzd8MTE1ODE0MzR8MTUwNDcxMTQyMzAwMA==/500x', 'O livro Pai rico, pai pobre narra a história de Robert Kiyosaki e de seu amigo Mike. Ao longo de sua trajetória...','O livro Pai rico, pai pobre narra a história de Robert Kiyosaki e de seu amigo Mike. Ao longo de sua trajetória, Robert recebe orientações financeiras de seu próprio pai – o pai pobre – e do pai de Mike – o pai rico. suas próprias carreiras, eles carregam visões muito distintas quando se fala em lidar com o dinheiro.',7,1)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('Metas','2011', 'Best Seller', 1, 'https://m.media-amazon.com/images/I/51RCgVyCGpL._SY466_.jpg','Em 1900 havia cinco mil milionários apenas nos Estados Unidos. Com a chegada do novo milênio o número saltou para cinco milhões...','Em 1900 havia cinco mil milionários apenas nos Estados Unidos. Com a chegada do novo milênio o número saltou para cinco milhões. Até 2020 estima-se que 20 milhões de pessoas entrem no time dos rendimentos de sete dígitos. Em Metas, o especialista em treinamento empresarial Brian Tracy dá dicas e ferramentas para quem quer fazer parte desse seleto clube de privilegiados. Através do prático e comprovado processo de estabelecimento e realização de objetivos, é possível realizar muito em pouco tempo.',3,4)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('Como Fazer Amigos e Influenciar as pessoas', '1936','Editora Sextante', 1,'https://cdn.kobo.com/book-images/718cd3aa-cbfa-4987-b772-bbc7cff67ea2/1200/1200/False/como-fazer-amigos-e-influenciar-pessoas-1.jpg','Dale Carnegie cedo percebeu que o êxito tem pouco a ver com conhecimentos profissionais. O mundo pertence a quem consegue expressar as suas ideias, assumir a liderança e entusiasmar os outros...','Dale Carnegie cedo percebeu que o êxito tem pouco a ver com conhecimentos profissionais. O mundo pertence a quem consegue expressar as suas ideias, assumir a liderança e entusiasmar os outros. Com base nesta crença, construiu um formidável império na área da formação, hoje presente em 80 países. Como Fazer Amigos e Influenciar Pessoas é o mais bem sucedido livro da história da literatura motivacional.',3,5)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('A psicologia financeira','15 março 2021','HarperCollins',1,'https://alvaroflores.com.br/wp-content/uploads/2022/08/81ehvI03NYS.jpeg','O sucesso financeiro tem menos a ver com a sua inteligência e muito mais a ver com o seu comportamento. E a forma como alguém se comporta é uma coisa difícil de se ensinar, mesmo para pessoas bastante inteligentes.','O sucesso financeiro tem menos a ver com a sua inteligência e muito mais a ver com o seu comportamento. E a forma como alguém se comporta é uma coisa difícil de se ensinar, mesmo para pessoas bastante inteligentes. A maneira como lidamos com o dinheiro — finanças pessoais, investimentos, decisões de negócios — costuma ser explicada como um campo puramente matemático, no qual dados e fórmulas nos dizem o que fazer. A verdade, porém, é que grandes decisões monetárias não são tomadas diante de uma planilha, mas durante jantares com a família e reuniões com os colegas de trabalho. Além disso, cada uma delas é um reflexo da história pessoal e das dificuldades enfrentadas pelo indivíduo que as tomou.',7,6)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('Os segredos da mente milionária','1 agosto 1992','Editora Sextante',1,'https://m.media-amazon.com/images/I/81fxmkE+tNL._AC_UF1000,1000_QL80_.jpg','T. Harv Eker desmistifica o motivo pelo qual algumas pessoas estão destinadas à riqueza e outras a uma vida de dureza. Se você quer conhecer as causas fundamentais do sucesso, leia este livro." – Robert G. Allen, autor de O milionário em um minuto','T. Harv Eker desmistifica o motivo pelo qual algumas pessoas estão destinadas à riqueza e outras a uma vida de dureza. Se você quer conhecer as causas fundamentais do sucesso, leia este livro." – Robert G. Allen, autor de O milionário em um minuto. Se as suas finanças andam na corda bamba, talvez esteja na hora de você refletir sobre o que T. Harv Eker chama de "o seu modelo de dinheiro" – um conjunto de crenças que cada um de nós alimenta desde a infância e que molda o nosso destino financeiro, quase sempre nos levando para uma situação difícil.',7,7)
INSERT INTO tb_books (title, book_year, publisher, edition, img_url, short_summary, long_summary, category_id, author_id) VALUES('Comporte-se Como Uma Dama, Pense Como Um Homem','4 fevereiro 2014','Nova Fronteira',1,'https://martinsfontespaulista.vteximg.com.br/arquivos/ids/437701-800-800/782000_ampliada.jpg?v=637264020365600000','Esqueça tudo o que já foi dito sobre os homens. Apague os mitos, as teorias, tudo o que sua mãe ensinou, as amigas disseram, aquilo que leu em revistas ou viu na televi¬são. Faça o que milhares de mulheres ao redor do mundo já fizeram: pegue os princípios, as regras e as dicas deste manual e use-os para se antecipar às manobras masculinas, para armar sua defesa e seu ataque.','Esqueça tudo o que já foi dito sobre os homens. Apague os mitos, as teorias, tudo o que sua mãe ensinou, as amigas disseram, aquilo que leu em revistas ou viu na televi¬são. Faça o que milhares de mulheres ao redor do mundo já fizeram: pegue os princípios, as regras e as dicas deste manual e use-os para se antecipar às manobras masculinas, para armar sua defesa e seu ataque. Por vezes engraçado, por vezes categórico, mas sempre verdadeiro, Comporte-se como uma dama, pense como um homem é o livro que toda mulher precisa ler se quiser finalmente montar o quebra-cabeças mais difícil de todos: a mente masculina.',3,8)

INSERT INTO tb_belonging (book_id, category_id, position) values(1,2,0)
INSERT INTO tb_belonging (book_id, category_id, position) values(2,2,1)

INSERT INTO tb_belonging (book_id, category_id, position) values(3,7,0)
INSERT INTO tb_belonging (book_id, category_id, position) values(6,7,1)
INSERT INTO tb_belonging (book_id, category_id, position) values(7,7,2)

INSERT INTO tb_belonging (book_id, category_id, position) values(4,3,0)
INSERT INTO tb_belonging (book_id, category_id, position) values(5,3,1)
INSERT INTO tb_belonging (book_id, category_id, position) values(8,3,2)


